/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LobbyLobbyCodeRouteRouteImport } from './routes/lobby/$lobbyCode/route'
import { Route as LobbyLobbyCodeIndexRouteImport } from './routes/lobby/$lobbyCode/index'
import { Route as LobbyLobbyCodeGameRouteRouteImport } from './routes/lobby/$lobbyCode/game/route'
import { Route as LobbyLobbyCodeGameIndexRouteImport } from './routes/lobby/$lobbyCode/game/index'
import { Route as LobbyLobbyCodeGameResultRouteImport } from './routes/lobby/$lobbyCode/game/result'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyLobbyCodeRouteRoute = LobbyLobbyCodeRouteRouteImport.update({
  id: '/lobby/$lobbyCode',
  path: '/lobby/$lobbyCode',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyLobbyCodeIndexRoute = LobbyLobbyCodeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LobbyLobbyCodeRouteRoute,
} as any)
const LobbyLobbyCodeGameRouteRoute = LobbyLobbyCodeGameRouteRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => LobbyLobbyCodeRouteRoute,
} as any)
const LobbyLobbyCodeGameIndexRoute = LobbyLobbyCodeGameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LobbyLobbyCodeGameRouteRoute,
} as any)
const LobbyLobbyCodeGameResultRoute =
  LobbyLobbyCodeGameResultRouteImport.update({
    id: '/result',
    path: '/result',
    getParentRoute: () => LobbyLobbyCodeGameRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lobby/$lobbyCode': typeof LobbyLobbyCodeRouteRouteWithChildren
  '/lobby/$lobbyCode/game': typeof LobbyLobbyCodeGameRouteRouteWithChildren
  '/lobby/$lobbyCode/': typeof LobbyLobbyCodeIndexRoute
  '/lobby/$lobbyCode/game/result': typeof LobbyLobbyCodeGameResultRoute
  '/lobby/$lobbyCode/game/': typeof LobbyLobbyCodeGameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lobby/$lobbyCode': typeof LobbyLobbyCodeIndexRoute
  '/lobby/$lobbyCode/game/result': typeof LobbyLobbyCodeGameResultRoute
  '/lobby/$lobbyCode/game': typeof LobbyLobbyCodeGameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lobby/$lobbyCode': typeof LobbyLobbyCodeRouteRouteWithChildren
  '/lobby/$lobbyCode/game': typeof LobbyLobbyCodeGameRouteRouteWithChildren
  '/lobby/$lobbyCode/': typeof LobbyLobbyCodeIndexRoute
  '/lobby/$lobbyCode/game/result': typeof LobbyLobbyCodeGameResultRoute
  '/lobby/$lobbyCode/game/': typeof LobbyLobbyCodeGameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lobby/$lobbyCode'
    | '/lobby/$lobbyCode/game'
    | '/lobby/$lobbyCode/'
    | '/lobby/$lobbyCode/game/result'
    | '/lobby/$lobbyCode/game/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lobby/$lobbyCode'
    | '/lobby/$lobbyCode/game/result'
    | '/lobby/$lobbyCode/game'
  id:
    | '__root__'
    | '/'
    | '/lobby/$lobbyCode'
    | '/lobby/$lobbyCode/game'
    | '/lobby/$lobbyCode/'
    | '/lobby/$lobbyCode/game/result'
    | '/lobby/$lobbyCode/game/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LobbyLobbyCodeRouteRoute: typeof LobbyLobbyCodeRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby/$lobbyCode': {
      id: '/lobby/$lobbyCode'
      path: '/lobby/$lobbyCode'
      fullPath: '/lobby/$lobbyCode'
      preLoaderRoute: typeof LobbyLobbyCodeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby/$lobbyCode/': {
      id: '/lobby/$lobbyCode/'
      path: '/'
      fullPath: '/lobby/$lobbyCode/'
      preLoaderRoute: typeof LobbyLobbyCodeIndexRouteImport
      parentRoute: typeof LobbyLobbyCodeRouteRoute
    }
    '/lobby/$lobbyCode/game': {
      id: '/lobby/$lobbyCode/game'
      path: '/game'
      fullPath: '/lobby/$lobbyCode/game'
      preLoaderRoute: typeof LobbyLobbyCodeGameRouteRouteImport
      parentRoute: typeof LobbyLobbyCodeRouteRoute
    }
    '/lobby/$lobbyCode/game/': {
      id: '/lobby/$lobbyCode/game/'
      path: '/'
      fullPath: '/lobby/$lobbyCode/game/'
      preLoaderRoute: typeof LobbyLobbyCodeGameIndexRouteImport
      parentRoute: typeof LobbyLobbyCodeGameRouteRoute
    }
    '/lobby/$lobbyCode/game/result': {
      id: '/lobby/$lobbyCode/game/result'
      path: '/result'
      fullPath: '/lobby/$lobbyCode/game/result'
      preLoaderRoute: typeof LobbyLobbyCodeGameResultRouteImport
      parentRoute: typeof LobbyLobbyCodeGameRouteRoute
    }
  }
}

interface LobbyLobbyCodeGameRouteRouteChildren {
  LobbyLobbyCodeGameResultRoute: typeof LobbyLobbyCodeGameResultRoute
  LobbyLobbyCodeGameIndexRoute: typeof LobbyLobbyCodeGameIndexRoute
}

const LobbyLobbyCodeGameRouteRouteChildren: LobbyLobbyCodeGameRouteRouteChildren =
  {
    LobbyLobbyCodeGameResultRoute: LobbyLobbyCodeGameResultRoute,
    LobbyLobbyCodeGameIndexRoute: LobbyLobbyCodeGameIndexRoute,
  }

const LobbyLobbyCodeGameRouteRouteWithChildren =
  LobbyLobbyCodeGameRouteRoute._addFileChildren(
    LobbyLobbyCodeGameRouteRouteChildren,
  )

interface LobbyLobbyCodeRouteRouteChildren {
  LobbyLobbyCodeGameRouteRoute: typeof LobbyLobbyCodeGameRouteRouteWithChildren
  LobbyLobbyCodeIndexRoute: typeof LobbyLobbyCodeIndexRoute
}

const LobbyLobbyCodeRouteRouteChildren: LobbyLobbyCodeRouteRouteChildren = {
  LobbyLobbyCodeGameRouteRoute: LobbyLobbyCodeGameRouteRouteWithChildren,
  LobbyLobbyCodeIndexRoute: LobbyLobbyCodeIndexRoute,
}

const LobbyLobbyCodeRouteRouteWithChildren =
  LobbyLobbyCodeRouteRoute._addFileChildren(LobbyLobbyCodeRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LobbyLobbyCodeRouteRoute: LobbyLobbyCodeRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
